[package]
name = "vsock"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-vsock = { workspace = true}
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
bincode = "1.3"
futures = "0.3"
libc = "0.2" 
