[package]
name = "test_program"
version = "0.1.1"
authors = ["Chris Schnabl"]
description = "TODO"
license = "Apache-2.0"
edition = "2018"

[dependencies]
#llama_cpp = "0.3.2"
llama-cpp-2 = "0.1.69"
anyhow = "1.0.95"